### ISSUE TITLE
Tk bad argument "zoomed"

### ISSUE THREAD

**Issue by albertmeronyo** [mhbeals/nisaba#12]
"zoomed" doesn't seem a valid argument for a window state (at least in Linux Ubuntu 19.09):

```
 File "/home/amp/.local/lib/python3.7/site-packages/nisaba/database_display.py", line 752, in collection_selector
    self.collection_selection_window.state('zoomed')
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1981, in wm_state
    return self.tk.call('wm', 'state', self._w, newstate)
_tkinter.TclError: bad argument "zoomed": must be normal, iconic, or withdrawn
```

**Comment by mhbeals** [comment]
I will investigate. Works currently on OS and Windows so must be a Linux-specific command I need to use

**Comment by mhbeals** [comment]
@albertmeronyo Can you confirm this fix works on your version of Linux before we push to release?

**Comment by albertmeronyo** [comment]
Yes, works now on Linux too

**Comment by Amsilva3** [comment]
I'm using tkinter on linux mint 21 and this zoomed function is not working, and the -alpha attribute doesn't give an error but it doesn't change either.
