### ISSUE TITLE
Change Metadata to Open Citations Format (SPAR)

### ISSUE THREAD

**Issue by mhbeals** [mhbeals/nisaba#2]
More elastic and up-to-date model is available at [Open Citations](https://opencitations.net/) and their [data model](https://figshare.com/articles/Metadata_for_the_OpenCitations_Corpus/3443876)

- [x] Book (Full Text Publication)
- [x] Article (Segment in Serial Publication)
- [x] Chapter (Segment in Full Text Publication)
- [x] Image
- [x] Archival Folder
- [x] Recording

**Comment by mhbeals** [comment]
@albertmeronyo A way needs to be included to attach URI information for metadata to config schema.  Would the best way be 

- [ ] to have another config file / config screen 
- [ ] have a line at the top of the config file setting vocab URIref

**Comment by albertmeronyo** [comment]
Sounds good (eventually this could pull from the DH ontology repo, but for now a config screen with preferred namespaces/vocabulary terms to map to should be fine)

**Comment by mhbeals** [comment]
Okay. Great! I have now officially broken most of the `rdf_mapper` function by changing all the field names in collection/item/segment bibliographic files to SPAR standards.  I will be doing to final-ish edits to the naming conventions this week so best not to re-map just yet.

The final aim will be a drop down on the screen that let's you choose a bibliographic entry type (book, article, etc) and then display those fields (Zotero like) so that people can use our standard types or add files of their own. This means being able to package classes/properties "on the fly" and will require some thought on the most streamlined way to do it.

**Comment by mhbeals** [comment]
This has largely been implemented for JSON

While most collections/items/segment information is flat (all under the same level "object") there is some difficulty for certain types (book chapters/journal articles) where the dc:title of the chapter / article should be nested as "part of" dc:title'ed book / journal.  I am not sure how best to inform the RDF parser of this structure since all of it will be under "collection"

My initial thought is that this structure should be encoded in the configuration file (changing these from YAML to .ini?)

Thoughts @albertmeronyo ?
