### ISSUE TITLE
Dependencies Installer

### ISSUE THREAD

**Issue by mhbeals** [mhbeals/nisaba#6]
Create dependencies installer

- [x] conda
- [x] pip

**Comment by albertmeronyo** [comment]
PyPI will require a license before we can publish this as a pip package, which one should we use?

**Comment by mhbeals** [comment]
I would suggest GNU AGPLv3. Do you have any objections?

**Comment by albertmeronyo** [comment]
pip packaging and uploads Implemented in bea0adf88f0e97c1dca7259057f99ae67a3cde11
(minor additions in subsequent commits)

**Comment by mhbeals** [comment]
Conda package uploaded to Anaconda Cloud (https://anaconda.org/mhbeals/nisaba)
